"""Add days_to_hire_stats table

Revision ID: 8fcad645974f
Revises: 991ecb2bf269
Create Date: 2025-03-01 14:50:25.197855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcad645974f'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('avg_days_to_hire', sa.Float(), nullable=False),
    sa.Column('min_days_to_hire', sa.Integer(), nullable=False),
    sa.Column('max_days_to_hire', sa.Integer(), nullable=False),
    sa.Column('job_postings_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['standard_job_id'], ['public.standard_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_job_id', 'country_code', name='unique_standard_job_country'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire_stats', schema='public')
    # ### end Alembic commands ###
